- eds/styles/styles.css
Partial fix for #253 
It fixes the color and background in sections with calcite-mode-dark and also centers the content in default-content-wrapper
Before:
After:
Test URLs:
- Original: https://www.esri.com/fr-fr/about/about-esri/overview
- Before: https://main--esri-eds--esri.aem.live/fr-fr/about/about-esri/overview
- After: https://fix-themebackground--esri-eds--esri.aem.live/fr-fr/about/about-esri/overview
> Fix default section styling

- fstab.yaml
Fix #<gh-issue-id>
Test URLs:
- After: https://sharepoint-revert--esri-eds--esri.aem.live/
> fix: revert to Abode sharepoint

- eds/blocks/storyteller/storyteller.css
- eds/blocks/storyteller/storyteller.js
Convert all button links into calcite buttons
Fix #278 
Test URLs:
- After: https://storyteller-calcite-cta--esri-eds--esri.aem.live/
1. Confirm buttons are calcite-button element in web inspector. <calcite-button>
> Convert link buttons to calcite buttons for Storyteller

- eds/styles/styles.css
Fix #267 
Test URLs:
- After: https://mghover--esri-eds--esri.aem.live/en-us/about/about-esri/europe/overview
> fix: flip opacity colors for light/dark

- eds/scripts/aem.js
@alexcarol  `${window.hlx.codeBasePath}` was returning the string `eds` resulting in 404 for icons. See Jane Goodall tab. I added an icon in my draft version.
returns ==> /eds/icons/customer-satisfaction-48.svg
correct path ==> /icons/customer-satisfaction-48.svg
Fix #<gh-issue-id>
Test URLs:
- After: https://iconpath--esri-eds--esri.aem.page/drafts/timw/overview
> Fix: Icon path

- eds/blocks/storyteller/storyteller.css
- eds/blocks/storyteller/storyteller.js
Normalize foreground image/video size and foreground copy gray background. 
Fix #274
Test URLs:
- After: https://storytellerBtnAlign--esri-eds--esri.aem.live/
> Storyteller foreground video/image size 

- eds/blocks/hero/hero.css
- eds/blocks/hero/hero.js
Still missing background image. For now assuming if no image, video link is foreground image
Fix #271
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/artificial-intelligence/overview
- After: https://banner--esri-eds--esri.aem.live/en-us/artificial-intelligence/overview
> feat: in no img, assume video link is foreground

- eds/blocks/storyteller/storyteller.css
- eds/blocks/storyteller/storyteller.js
Fix #273 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/location
- After: https://storytellerIcon--esri-eds--esri.aem.live/
> Storyteller Missing Icons on Location Page

- eds/blocks/storyteller/storyteller.js
Fix #254
Test URLs:
- After: https://storytellerAutoPlay--esri-eds--esri.aem.live/
> Storyteller autoplay video once 

- eds/styles/styles.css
For 'unblocked' content such as the ["Who uses AI and Location Intelligence" section](https://contentwrap--esri-eds--esri.aem.live/en-us/artificial-intelligence/overview#:~:text=Who%20uses%20AI%20and%20location%20intelligence%3F)
Fix #316
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/artificial-intelligence/overview
- After: https://contentwrap--esri-eds--esri.aem.live/en-us/artificial-intelligence/overview
> feat: set max width on content wrapper

- eds/blocks/large-content-stack/large-content-stack.js
Fixed the Calcite button decorator function so that it adds an icon. Added JSDoc blocks to the functions.
Fix #296 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/company
- Before: https://main--esri-eds--esri.aem.page/en-us/about/about-esri/company
- After: https://296-lcs-button-option--esri-eds--esri.aem.page/en-us/about/about-esri/company
> fix(large-content-stack): button decorator function

- eds/blocks/tabs/tabs.js
Fix #320 
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/artificial-intelligence/overview#at&t
- After: https://tabselected--esri-eds--esri.aem.live/en-us/artificial-intelligence/overview#at&t
> fix: only active tab selected

- eds/blocks/centered-content-switcher/centered-content-switcher.js
Changed image size to `2560` in order to fix the background image size issue.
Fix #331
Test URLs:
- After: https://331-centered-content-switcher-poor-background-image-resolution--esri-eds--esri.aem.live/en-us/about/about-esri/americas
> fix(centered-content-switcher): background image size

- eds/blocks/centered-content-switcher/centered-content-switcher.js
- eds/blocks/elastic-content-strip/elastic-content-strip.js
Fix #335
Test URLs:
Fixed centered-content-switcher:
Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview
After: https://fix-contentswitcher--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview
Fixed elastic-content-strip:
Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/americas
After: https://fix-contentswitcher--esri-eds--esri.aem.live/en-us/about/about-esri/americas
> Add support for calcite-button in centered-content-switcher and elastic-content-strip

- eds/blocks/local-navigation/local-navigation.js
Changed the hard-coded value for `currDomain` so that other local development ports have proper domain resolution.
Fix #344
Test URLs:
- After: https://344-local-navigation-localhost--esri-eds--esri.aem.live/
> fix(local-navigation): correct domain resolution for URL updates

- .vscode/settings.json
Created a shared VSCode settings file for the project so that developers all have the same settings configured for their IDE.
Fix #376
Test URLs:
- After: https://vscode-settings--esri-eds--esri.aem.live/
> chore(vscode): add editor settings for ESLint and Stylelint integration

- eds/blocks/local-navigation/local-navigation.css
Fix #383 
Test URLs:
- After: https://navcolor--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview
> fix: localnav title color

- eds/scripts/scripts.js
Prevent from local navigation from loading within tabs
Test URLs:
- After: https://fix-tabslocalnavigation--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/overview
> Fix local navigation on pages with tabs

- eds/blocks/tabs/tabs.css
Adjusting the sizes of tabs and alignment.
Fix #396
Test URLs:
- After: https://tabsize--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/overview
> feat: adjust tab sizes, align to bottom

- eds/scripts/scripts.js
Fix #400
Test URLs:
- After: https://decorateCalciteRemove--esri-eds--esri.aem.live/
> fix: script.js remove decorateToCalcite routine.

- eds/blocks/form/form.js
FQDN was added to the `aemFieldServiceBasePath` parameter, and unicode characters were replaced.
Fix #403
Test URLs:
- After: https://403-form-component--esri-eds--esri.aem.live/
> fix(form): update URLs for aemFieldServiceBasePath and pardotHandler

- eds/blocks/local-navigation/local-navigation.css
Test: 
1.  full desktop > 1440px 
2. switch from calcite-dark-mode to calcite-light-mode. confirm local nav background remains dark. 
Fix #408
Test URLs:
- After: https://localNavLightMode--esri-eds--esri.aem.live/
> Local Nav adjust for light mode theme

- eds/blocks/local-navigation/local-navigation.css
- eds/blocks/local-navigation/local-navigation.js
Implement subitem functionality desktop and mobile.
Fix #415 
Test URLs:
- After: https://localnavsubitems--esri-eds--esri.aem.live/en-us/capabilities/real-time/overview
> Local Nav sub items functionality

- eds/blocks/quote/quote.js
- eds/scripts/aem.js
- eds/scripts/scripts.js
Change decorateIcon to use Esri DAM for image paths.
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/capabilities/management
- After: https://iconpath--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/capabilities/management
> feat: change icon path

- eds/blocks/hero/hero.css
Background image compressed inwards needs object fix cover property.
Fix #432 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/spatial-analytics-data-science/overview
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/spatial-analytics-data-science/overview
- After: https://heroBgImage--esri-eds--esri.aem.live/en-us/capabilities/spatial-analytics-data-science/overview
> Hero Banner Background Image Cover

- eds/blocks/hero/hero.css
Align CTAs horizontally in desktop view and stack CTAs in mobile view.
Fix #426 
Test URLs:
- After: https://heroCTAs--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/overview
> Hero Banner align CTAs horizontally for desktop view

- eds/styles/styles.css
Not ideal, but adding `-64` to the sizing rule. 
Fix #437
Test URLs:
- After: https://iconsize--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/overview
> feat: update icon sizing

- eds/blocks/columns/columns.css
- eds/blocks/hero/hero.css
Enable Small and Center text variant. 
Fix #451 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/3d-gis/resources
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/resources
- After: https://smallHero--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/resources
@alexcarol we have a backgroundimg 'null' value.
> Hero Banner small center variant

- eds/blocks/cards/cards.css
Fix #440 
Test URLs:
- After: https://cardspcaing--esri-eds--esri.aem.page/en-us/capabilities/indoor-gis/overview
> fix(ui): updated spacing between title and description for cards default

- eds/blocks/columns/columns.css
Adding a gutter for fifty fifty / Column Block. Will adjust aligned for image in separate PR. 
Fix #454
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/data-management (50/50)
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/data-management  (50/50)
- After: https://fiftyGutter--esri-eds--esri.aem.live/en-us/capabilities/data-management  (50/50)
- Original: https://www.esri.com/en-us/capabilities/data-management (Media Split)
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/data-management  (Media Split)
- After: https://fiftyGutter--esri-eds--esri.aem.live/en-us/capabilities/data-management  (Media Split)
> Column / 50-50 & Media Split add start/end padding 

- eds/blocks/columns/columns.css
Column set order for content to appear above image on mobile regardless of order in desktop view.
Fix #456 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/data-management **(50/50)**
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/data-management **(50/50)**
- After: https://columnOrder--esri-eds--esri.aem.live/en-us/capabilities/data-management  **(50/50)**
- Original: https://www.esri.com/en-us/capabilities/data-management **(Media Split)**
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/data-management **(Media Split)**
- After: https://columnOrder--esri-eds--esri.aem.live/en-us/capabilities/data-management  **(Media Split)**
> Column / 50-50 & Media Split Mobile content order

- eds/blocks/cards/cards.js
Modified JS to update the title element to H3 for all versions of cards. 
Fix #429 
Test URLs:
- After: https://cardtitleupdate--esri-eds--esri.aem.live/en-us/capabilities/data-management
- After: https://cardtitleupdate--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview
> feat(ui): updated title for the cards to be h3

- .stylelintrc.json
- package-lock.json
- package.json
Added the Stylelint Order plugin and configured it to alphabetize CSS properties.
Fix #467
Test URLs:
- After: https://stylelint-order--esri-eds--esri.aem.live/
> feat(stylelint): add stylelint-order plugin and alphabetical rules

- eds/blocks/call-to-action/call-to-action.css
- eds/blocks/cards/cards.css
- eds/blocks/centered-content-switcher/centered-content-switcher.css
- eds/blocks/columns/columns.css
- eds/blocks/form/form.css
- eds/blocks/header/header.css
- eds/blocks/hero/hero.css
- eds/blocks/image-switcher/image-switcher.css
- eds/blocks/large-content-stack/large-content-stack.css
- eds/blocks/local-navigation/local-navigation.css
- eds/blocks/location-presence/location-presence.css
- eds/blocks/map/map.css
- eds/blocks/media-gallery/media-gallery.css
- eds/blocks/mosaic-reveal/mosaic-reveal.css
- eds/blocks/sidedrawer/sidedrawer.css
- eds/blocks/storyteller/storyteller.css
- eds/blocks/tabs/tabs.css
- eds/blocks/text/text.css
- eds/blocks/video-cards/video-cards.css
- eds/styles/fonts.css
- eds/styles/styles.css
Ran `stylelint --fix` on CSS to fix linter errors introduced by the updated configuration.
Fix #474 
Test URLs:
- After: https://474-stylelint-fix--esri-eds--esri.aem.live/
> style(css): reformat CSS with stylelint to fix linter errors

- eds/blocks/columns/columns.css
Fix #457 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/data-management **(50/50)**
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/data-management **(50/50)**
- After: https://colTopPad--esri-eds--esri.aem.live/en-us/capabilities/data-management  **(50/50)**
- Original: https://www.esri.com/en-us/capabilities/data-management **(Media Split)**
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/data-management **(Media Split)**
- After: https://colTopPad--esri-eds--esri.aem.live/en-us/capabilities/data-management  **(Media Split)**
> Column /  50-50 & Media Split bottom top padding mobile view

- eds/blocks/cards/cards.js
- eds/scripts/dom-helpers.js
- Added 'calcite-link' element as part of dom helpers.
- Updated JS, to generate calcite-link element for cards block.
- Updated JS, for the title of card to be H3.
Fix #466 
Test URLs:
- After: https://calcitelink--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/overview
> Added calcite link for cards

- eds/scripts/scripts.js
- eds/styles/styles.css
Add intersection observer timing to the animations; update the delay var. 
Look at the big numbers in the "Location-based" block. 
Fix #480
Test URLs:
- After: https://animate--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> feat: add intersection observer and animation timing

- eds/blocks/columns/columns.css
- eds/blocks/columns/columns.js
Align CTA buttons in same row on desktop, stack on mobile view. 
Fix #458
**Test URLs (50/50):**
- Original: https://www.esri.com/en-us/capabilities/mapping/overview
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/mapping/overview  
- After: https://ctaAlign--esri-eds--esri.aem.live/en-us/capabilities/mapping/overview 
**Test URLs (Media Split):**
- Original: https://www.esri.com/en-us/capabilities/geoai/overview
- After: https://ctaAlign--esri-eds--esri.aem.live/en-us/capabilities/geoai/overview
> Columns Align CTAs in row

- eds/blocks/cards/cards.css
- Removed extra spacing between icon and content
Fix #438 
Test URLs:
- After: https://tlsspacing--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/overview
> updated spacing for tls equivalent

- eds/blocks/columns/columns.css
Fix #486 
Test URLs: (media split)
- Original: https://www.esri.com/en-us/capabilities/geoai/overview
- After: https://imgAlign--esri-eds--esri.aem.live/en-us/capabilities/geoai/overview
Test URLs: (50/50)
- After: https://imgAlign--esri-eds--esri.aem.live/en-us/capabilities/data-management
> Media Split align image towards center half of viewport 

- eds/blocks/columns/columns.css
Fix #485 
Test URLs: (media split)
- Original: https://www.esri.com/en-us/capabilities/geoai/overview
- After: https://alignTxtC--esri-eds--esri.aem.live/en-us/capabilities/geoai/overview
Test URLs: (50/50)
- After: https://alignTxtC--esri-eds--esri.aem.live/en-us/capabilities/data-management
> Media Split center text for mobile/tablet

- eds/blocks/elastic-content-strip/elastic-content-strip.css
- eds/blocks/elastic-content-strip/elastic-content-strip.js
- Updated text color to match prod.
- Updated button to a calcite link 
Fix #488 
Test URLs:
- After: https://ecsbutton--esri-eds--esri.aem.live/en-us/capabilities/real-time/overview
> ECS-update button to calcite link and text color

- eds/blocks/image-switcher/image-switcher.css
**Fixed the following issues:**
- Images are in oval shape unlike round shape in prod.
- The sequence of image switcher cards is incorrect.
- Cards are not wrapped in the correct order.
Fix #493 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/capabilities/visualization-interpretation
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/capabilities/visualization-interpretation
- After: https://imageswitcher--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/capabilities/visualization-interpretation
> image switcher-updated styles

- eds/blocks/columns/columns.css
Hide Content Overflow in tablet view.
Fix #496 
Test URLs: **(50-50)**
- After: https://fiftyOverflow--esri-eds--esri.aem.live/en-us/capabilities/data-management
Test URLs: **(Media Text Split)**
- Original: https://www.esri.com/en-us/capabilities/indoor-gis/capabilities/indoor-data-collection
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/capabilities/indoor-data-collection
- After: https://fiftyOverflow--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/capabilities/indoor-data-collection
Test URLs: **(Media Split)**
- Original: https://www.esri.com/en-us/en-us/capabilities/geoai/overview
- Before: …
> 50-50 overflow hidden

- eds/blocks/columns/columns.css
- eds/blocks/columns/columns.js
Media Text Split wraps <picture> element inside a <p> element where as Media Split does not wrap <picture> element inside a <p> element. Add class 'column-p' to Media Text Split. This addition allows for style differences between Media Text Split and Media Split.
Fix #492
Test URLs: **(Media Text Split)**
- Original: https://www.esri.com/en-us/capabilities/indoor-gis/capabilities/indoor-data-collection
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/capabilities/indoor-data-collection
- After: https://mts50--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/capabilities/indoor-data-collection
Test URLs: **(Media Split)**
- Original: https://www.esri.com/en-us/en-us/capabilities/geoai/overview
- Before: …
> Media Text Split image container

- eds/blocks/columns/columns.css
- eds/blocks/columns/columns.js
Convert buttons to Calcite-Button and Calcite-Link
Fix #497 
Test URLs: (Media Split)
- Original: https://www.esri.com/en-us/capabilities/geoai/overview
- After: https://mtsCalcite--esri-eds--esri.aem.live/en-us/capabilities/geoai/overview
Test URLs: (50-50)
- After: https://mtsCalcite--esri-eds--esri.aem.live/en-us/capabilities/data-management
> Media Split Calcite Button

- eds/scripts/aem.js
- Have updated the if condition so it not only checks for the full url but also the relative path.
- This helps to cover the usecases with relative paths.
Fix #512 
Test URLs:
- Original: https://www.esri.com/en-us/digital-twin/overview
- Before: https://main--esri-eds--esri.aem.live/en-us/digital-twin/overview
- After: https://relativepath--esri-eds--esri.aem.live/en-us/digital-twin/overview
rendered as buttons which should actually be links:
> updated logic for links with relative paths

- eds/blocks/cards/cards.css
Cards simple with image(not an icon) are shrinking the image size. Update the css so it takes the image width and is not hidden.
Fix #519
Test URLs:
- After: https://cardsimpleimage--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/overview
> card simple with image - update width

- eds/blocks/cards/cards.css
- eds/blocks/cards/cards.js
- eds/blocks/tabs/tabs.css
- eds/blocks/tabs/tabs.js
- Eliminated redundant code from the tabs block, ensuring the cards block now loads as expected, utilizing only the relevant JS and CSS for the cards.
- Refactored JS to ensure consistent title updates to H3 across all card versions.
- This PR ensures that all card versions are fully functional and display as expected.
Fix #178 
Test URLs:
- After: https://cards--esri-eds--esri.aem.live/en-us/about/about-esri/americas
**Pages with cards(multiple versions):**
- http://main--esri-eds--esri.aem.live/en-us/about/about-esri/asia-pacific
- http://main--esri-eds--esri.aem.live/en-us/about/about-esri/mea-central-asia
- …
> JS updates for all card versions

- eds/blocks/columns/columns.js
Allow "esc" key to close modal
Fix #525 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/indoor-gis/capabilities/indoor-positioning-navigation
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/capabilities/indoor-positioning-navigation
- https://mtesc--esri-eds--esri.aem.page/en-us/capabilities/indoor-gis/capabilities/indoor-positioning-navigation
> Media Split Esc Close Modal

- eds/blocks/cards/cards.js
Updated JS to look for blockgroup cards and add cardsperrow-* based on number of li elements.
Fix #517 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/asia-pacific
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/asia-pacific
- After: https://blockgroup--esri-eds--esri.aem.live/en-us/about/about-esri/asia-pacific
> blockgroup cards

- eds/scripts/delayed.js
- eslint.config.mjs
- package-lock.json
- package.json
Adjusted ESLint configuration to ignore the `aem.js` file, updated NPM dependencies, removed `eslint-disable` directive from the `delayed.js` file.
Fix #510
Test URLs:
- After: https://510-eslint-warnings--esri-eds--esri.aem.live/
> fix(eslint): adjust configuration to resolve warnings

- eds/blocks/text/text.css
Replaced `word-wrap: break-word;` with `overflow-wrap: break-word;` since it is deprecated.
Fix #530 
Test URLs:
- After: https://530-text-styelint-error--esri-eds--esri.aem.live/
> fix(css): replace word-break with overflow-wrap

- eds/scripts/scripts.js
- eds/styles/styles.css
Update scripts to alternate image path for product icons. 
Fix #512
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/capabilities/visualization-interpretation
- Before: https://main--esri-eds--esri.aem.live/drafts/timw/visualization-interpretation
- After: https://iconpath--esri-eds--esri.aem.live/drafts/timw/visualization-interpretation
> feat: update Icon path for product icons

- eds/styles/styles.css
Formatting for plain content blocks. For Field Operations, top content block just below banner. Other content blocks on page as well. 
Fix #453
Test URLs:
- After: https://contentblock--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview
> fix: format content blocks

- eds/blocks/map/map.css
change background to cover; fix spacing
Fix #545
Test URLs:
- After: https://maps--esri-eds--esri.aem.live/en-us/about/about-esri/americas
> fix: spacing and background of map container

- eds/blocks/cards/cards.css
- eds/styles/styles.css
Update to default to bold for headers. 
Fix #555
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/company
- After: https://boldheaders--esri-eds--esri.aem.live/en-us/about/about-esri/company
> feat: remove fontweight overrides, bold by default

- eds/blocks/form/form.css
- eds/blocks/form/form.js
Implemented intersection observer into the Form component to prevent loading until the form is scrolled into view in the browser.
Fix #516 
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/resources
- After: https://516-psi-check--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/resources
> feat: optimize one-form loading with intersection observer

- eds/blocks/hero/hero.css
- eds/blocks/hero/hero.js
Check for any empty containers in hero. 
Remove from dom 
If content is `only-child` center content
Fix #563
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/3d-gis/resources
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/resources
- After: https://nullcheck--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/resources
> fat: banner Nullcheck

- eds/blocks/call-to-action/call-to-action.css
- eds/blocks/centered-content-switcher/centered-content-switcher.css
- eds/blocks/form/form.css
- Updated call to action section to match prod. Addressed only the CTA section, not the form.
- CCS bg image does not overlap on the form block.
- Form container title and text are center aligned
Fix #566 
Test URLs 1:
- After: https://calltoaction--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview
Test URLs 2:
- Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/resources
- Before: https://main--esri-eds--esri.aem.page/en-us/capabilities/imagery-remote-sensing/resources
- After: https://calltoaction--esri-eds--esri.aem.page/en-us/capabilities/imagery-remote-sensing/resources
> feat(css): call to action update

- eds/styles/styles.css
adjust spacing of content blocks, add hover state and resize plain buttons
Fix #559
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/technology#capabilities-of-esri-technology
- After: https://contentbutton--esri-eds--esri.aem.live/en-us/about/about-esri/technology#capabilities-of-esri-technology
> feat: content block sizing

- eds/scripts/delayed.js
- eds/styles/styles.css
Convert play button with title="video player" into embedded iframe. Center content.
Fix #565 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/overview
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/overview
- After: https://embedVideo--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/overview
-
> Embedded Iframe

- eds/blocks/mosaic-reveal/mosaic-reveal.css
- eds/styles/styles.css
Removing component-specific header sizing from Mosaic reveal for the left side. The left content is auto section, not block section. 
Adding `header-X` sizing classes. 
Allows authors to size headers in auto section content. Prefer over hard coded sizes. 
Fix #586 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/locations
- Before: https://main--esri-eds--esri.aem.live/drafts/timw/locations
- After: https://sizing--esri-eds--esri.aem.live/drafts/timw/locations
> feat: header sizing

- eds/blocks/media-gallery/media-gallery.css
- eds/blocks/tabs/tabs.css
Some unneccessary `inline-size: 100vw`. Blocks do that by default. In this case actually causing some blocks to be too wide. 
Fix #554
Test URLs:
- After: https://width--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> fix: page width overflow

- eds/blocks/media-gallery/media-gallery.css
Update overlay from light to a dark overlay
Fix #583 
Test URLs:
- After: https://mgOverlay--esri-eds--esri.aem.live/en-us/about/about-esri/europe/overview
-
> Media Gallery Dark Overlay

- eds/blocks/call-to-action/call-to-action.css
Restructured the CTA button that opens a oneform modal.
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/resources
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/resources
- After: https://ctabutton--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/resources
- After: https://ctabutton--esri-eds--esri.aem.live/en-us/about/about-esri/europe/overview
> CTA button that opens oneform modal

- eds/blocks/mosaic-reveal/mosaic-reveal.css
- eds/blocks/mosaic-reveal/mosaic-reveal.js
Switch from 'aria-hidden' to 'hidden' property.
Fix #602 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/locations
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/locations
- After: https://mrHidden--esri-eds--esri.aem.live/en-us/about/about-esri/locations
> Mosaic Reveal switch to hidden attribute

- eds/blocks/elastic-content-strip/elastic-content-strip.css
- eds/blocks/elastic-content-strip/elastic-content-strip.js
Background image is optional. 
Remove hard-coded from CSS. 
Allow for image to be authored
https://esriis.sharepoint.com/:w:/r/sites/EsriMarketingPublic/_layouts/15/Doc.aspx?sourcedoc=%7BD87725CE-47CA-4364-8392-881DDAE2C32C%7D&file=resources.docx&action=default&mobileredirect=true
Fix #412
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/drafts/timw/resources
- After: https://ecsimage--esri-eds--esri.aem.live/drafts/timw/resources
> feat(ecs): Remove hard coded image

- eds/blocks/cards/cards.css
- eds/blocks/cards/cards.js
Update to `cards.js` to check for `detailed-list` class
change to css for detailed list
change to css for `cardsperrow-` numbers 
Fix #612
Test URLs:
- After: https://detaillist--esri-eds--esri.aem.live/en-us/capabilities/real-time/overview
> feat(cards): Create detailed list version

- eds/blocks/tabs/tabs.css
- eds/blocks/tabs/tabs.js
Confirm tabs functions as normal for desktop and mobile viewports.
Fix #620 
Test URLs:
- After: https://tabsHidden--esri-eds--esri.aem.live/en-us/about/about-esri/technology
> Tabs Replace aria-hidden with hidden

- eds/blocks/tabs/tabs.css
Confirm the tab icons are aligned.
Fix #625 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/overview
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/overview
- After: https://tabicons--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/overview
> fix the tab icons alignment

- eds/blocks/call-to-action/call-to-action.css
CTA content off center on MOBILE view. 
Fix #632 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/real-time/features/visualization
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/visualization
- After: https://ctaMobile--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/visualization
> CTA Content Off Center

- tools/sidekick/config.json
Configure sidekick per documents 
https://www.aem.live/developer/configuring-aem-assets-sidekick-plugin
Fix #634
Test URLs:
- After: https://assets--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> feat(sidekick): Add assets to sidekick

- eds/blocks/sidedrawer/sidedrawer.js
Look for 'P' element text if h3 element is not present.
Fix #608 
Test URLs:
Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/overview
Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/overview
After: https://sidedrawerupdate--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/overview
> side drawer update

- eds/blocks/call-to-action/call-to-action.css
Updated CTA styling to fix a variation that has tow rows with CTA blocks.
Fix #611 
Test URLs:
- After: https://ctablock--esri-eds--esri.aem.live/en-us/capabilities/real-time/overview
> fix the cta block containers

- eds/blocks/media-gallery/media-gallery.css
- Added a new attribute to control the mg card overlay color.
- Added 'mg-card-dark' to add dark overlay for mg card irrespective of calcite mode.
Test URLs 1:
- After: https://mgcardcolor--esri-eds--esri.aem.live/en-us/about/about-esri/overview
Test URLs 2:
- After: https://mgcardcolor--esri-eds--esri.aem.live/en-us/about/about-esri/europe/overvie …
> Add a new attribute for mg card overlay color control

- eds/blocks/tabs/tabs.css
Fix #645 
Test URLs:
- After: https://tabsimage--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> fix(ui): Fix for the alignment of image inside tabs content

- eds/blocks/hero/hero.css
Fixed video size to take the full width of screen size on large devices.
Fix #652 
Test URLs:
- After: https://herovideo--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> fix(ui): fix for hero bg video on large devices[#652]

- eds/blocks/storyteller/storyteller.css
Fix #649 
Test URLs:
- After: https://storytellerfont--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> fix(ui): story teller font size update[#649]

- eds/blocks/tabs/tabs.css
Font size is updated for media split inside tab panel
Fix #650 
Test URLs:
- After: https://mediasplittab--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> fix(ui): media split tab panel font size[#650]

- eds/blocks/hero/hero.css
- Spacign and max inline size is updated for banner title.
- Tested on all viewports to match with prod.
- On desktop its aligned with global and secondary nav.
- On tablet and mobile, spacing on the left matches with prod but does not align with secondary nav
- Secondary nav alignment should be adjusted to match with prod
Fix #647 
Test URLs:
- After: https://bannertitle--esri-eds--esri.aem.live/
> banner title alignment[#647]

- eds/blocks/cards/cards.css
Removed spacing on the top for cards block.
Fix #651 
Test URLs:
- After: https://cardsspacing--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> updated cards block spacing on the top[#651]

- eds/blocks/storyteller/storyteller.css
Updated spacing for story teller to match with prod.
Fix #648 
Test URLs:
- After: https://storytellerspacing--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> Story teller spacing updates[#648]

- eds/blocks/call-to-action/call-to-action.css
Updated cta block to align horizontally and adjusted top and bottom spacing
Fix #664
Test URLs:
- After: https://ctaspacing--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> fix for cta spacing and alignment

- eds/blocks/tabs/tabs.css
- Removed box shadow for hover state of tab title.
- Updated the hover state underline color to match with prod.
Fix #667 
Test URLs:
- After: https://tabtitle--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> fix(ui): tab title hover state styling update[#667]

- eds/blocks/map/map.css
Updated map height to match with prod.
Fix #657 
Test URLs:
- After: https://mapheight--esri-eds--esri.aem.live/en-us/about/about-esri/americas
> Updated map container height(#657)

- eds/blocks/elastic-content-strip/elastic-content-strip.css
Font weight of ECS title is updated to bold to match with prod.
Fix #682 
Test URLs:
- After: https://ecstitle--esri-eds--esri.aem.live/en-us/about/about-esri/americas
> ECS title font weight[#682]

- eds/blocks/mosaic-reveal/mosaic-reveal.css
Fix #691 
Test URLs:
- After: https://msfont--esri-eds--esri.aem.live/en-us/about/about-esri/europe/overview
> fix(ui): updated font size for mosaic reveal[#691]

- eds/blocks/tabs/tabs.css
Fix #709 
Test URLs:
- After: https://tabimage--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> fix(ui): updated styles for tab panel image positioning[#709]

- eds/blocks/tabs/tabs.css
1. Adjusted spacing around the tab titles and also the alignment.
2. Spacing between tabs and content is adjusted via authoring.
Fix #723 
Test URLs:
- After: https://tabsspacing--esri-eds--esri.aem.live/en-us/about/about-esri/americas
> fix(ui): adjusted tab spacing[#723]

- eds/blocks/centered-content-switcher/centered-content-switcher.css
Fix #736
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/americas#rio-de-janeiro-uses-gis-for-smart-city-initiative
- After: https://ccstitle--esri-eds--esri.aem.live/en-us/about/about-esri/americas#rio-de-janeiro-uses-gis-for-smart-city-initiative
> fix(ccs): remove font-weight-normal from h2

- eds/blocks/hero/hero.css
- eds/blocks/hero/hero.js
- Added play/pause controls for Hero block background video.
- Works as prod version.
- Added code for looping the video when needed.
Fix #717 
Test URLs:
- After: https://herovideocontrols--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> fix(ui): Added play pause controls to hero bg video[#717]

- eds/blocks/large-content-stack/large-content-stack.css
Adjust top padding above h2 title to match PROD
https://www.esri.com/en-us/about/about-esri/company
Fix #726 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/company
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/company
- After: https://lcsH2--esri-eds--esri.aem.live/en-us/about/about-esri/company
> Large Content Stack Fix Top Padding

- eds/scripts/delayed.js
Fix #755 
Test URLs:
- After: https://analyticsfix--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> Load analytics attributes after the page loads[#755]

- eds/blocks/call-to-action/call-to-action.css
- eds/blocks/location-presence/location-presence.css
- eds/blocks/map/map.css
- eds/blocks/mosaic-reveal/mosaic-reveal.css
All titles should be bold; removing overrides.
Fix #766 
Test URLs:
- After: https://titles--esri-eds--esri.aem.live/en-us/about/about-esri/overview
> fix(titles): ensure all are bold

- eds/blocks/hero/hero.css
- eds/blocks/hero/hero.js
- Play/Pause button now shows up only when there is a background video.
- Headline and button are centered.
- Buttons are converted to calcite.
- The discrepancy we're seeing with the background image is due to differences in how it's rendered: on production, the background image is applied via the style attribute using background-image, whereas on the EDS side, the image is rendered as DM image.
Fix #774 
Test URLs:
- After: https://herobutton--esri-eds--esri.aem.live/en-us/about/about-esri/americas
> fix(herobutton): fixed multiple issues related to hero button[#774]

- eds/blocks/centered-content-switcher/centered-content-switcher.css
- eds/blocks/centered-content-switcher/centered-content-switcher.js
- Updated styles for content in CCS.
- Added quote style 
- Re-authored the background images for all slides.
- EDS live url might look broken because of the quote addition. It will be fixed once the code is merged.
Fix #775 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/asia-pacific
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/asia-pacific
- After: https://ccsstyles--esri-eds--esri.aem.live/en-us/about/about-esri/asia-pacific?query
> Centered content switcher - Styles update[775]

- eds/scripts/scripts.js
- eslint.config.mjs
An interesting feature of the media bus is that it is "flat", meaning that the "media" files can be found at any level, so this way the CDN can serve them.
Test URLs:
- After: https://image-cdn-fix--esri-eds--esri.aem.live/
> Request images at /eds/... instead to bypass cdn issues
