Esri/esri-eds

eds/styles/styles.css
Fix #262
Test URLs:
- After: https://centerText--esri-eds--esri.aem.live/
=> feat: add center class

eds/blocks/hero/hero.css, eds/blocks/hero/hero.js
Fix #279
Test URLs:
- After: https://heroHideMp4--esri-eds--esri.aem.live/
=> Hero Banner Hide Mp4 Link and Handle Console Error

eds/blocks/mosaic-reveal/mosaic-reveal.css, eds/blocks/mosaic-reveal/mosaic-reveal.js
fix console error regarding calcite link
Fix #292
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/location
- Before: https://main--esri-eds--esri.aem.page/en-us/about/about-esri/locations
- After: https://mosaicRevealExpand--esri-eds--esri.aem.page/en-us/about/about-esri/locations
=> Mosiac Reveal Expand Button Fix 

eds/blocks/large-content-stack/large-content-stack.css, eds/blocks/large-content-stack/large-content-stack.js
Fix #265 
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/company
- After: https://lcs--esri-eds--esri.aem.live/en-us/about/about-esri/company
=> feat: fix layout and images 

eds/blocks/tabs/tabs.css, eds/blocks/tabs/tabs.js
Fix #270 
Test URLs:
- After: https://tabspacing--esri-eds--esri.aem.live/en-us/about/about-esri/overview
=> fix: Tab spacing

eds/styles/styles.css
Adjust global box-sizing styles.
Fix #300
Test URLs:
- After: https://feat-global-box-sizing--esri-eds--esri.aem.live/
=> feat: change global box sizing styles

eds/styles/styles.css
Fix #266 
Test URLs:
- After: https://iconsize--esri-eds--esri.aem.live/en-us/about/about-esri/europe/overview
=> feat: size icon based on authored size

eds/blocks/tabs/tabs.js
Test URLs:
Remote sensing > resources (fixed)
Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/resources
After: https://fix-tabs--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/resources
About overview (unchanged):
Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/overview#science
After: https://fix-tabs--esri-eds--esri.aem.live/en-us/about/about-esri/overview#science
=> Fix broken tabs

eds/blocks/elastic-content-strip/elastic-content-strip.css
Elastic Content Strip: Fix padding issues, remove redundant styles, and fix formatting (Stylelint) issues.
Fix #304 
Test URLs:
- After: https://299-elastic-content-strip-padding-and-sizing--esri-eds--esri.aem.live/en-us/about/about-esri/europe/overview
=> style(css): fix padding and remove redundant styles

eds/blocks/hero/hero.css, eds/blocks/hero/hero.js
Check for images and video. Add video to foreground or background as needed; checking other conditions. 
Fix #295 
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/drafts/timw/new-hero/about/overview
- After: https://hero--esri-eds--esri.aem.live/drafts/timw/new-hero/about/overview
=> Hero - udpate video renders

eds/blocks/columns/columns.css
Fix #313 
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/digital-twin/overview
- After: https://mediasplit--esri-eds--esri.aem.page/en-us/digital-twin/overview
=> Mediasplit

eds/blocks/elastic-content-strip/elastic-content-strip.css, eds/styles/styles.css
Fix #318
Test URLs:
- Before: https://main--esri-eds--esri.aem.page/en-us/about/about-esri/mea-central-asia
- After: https://iconfilter--esri-eds--esri.aem.page/en-us/about/about-esri/mea-central-asia
=> Icon filter

eds/blocks/columns/columns.css, eds/blocks/tabs/tabs.css, eds/styles/styles.css
feat: refactor basic styles, remove font styles form tabs, update columns for media split
Fix #272
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/artificial-intelligence/overview#fedex
- After: https://mediasplit--esri-eds--esri.aem.live/en-us/artificial-intelligence/overview#fedex
=> Update styles for Media Split

eds/blocks/storyteller/storyteller.css, eds/blocks/storyteller/storyteller.js
Update playbutton from square to rounded style 
Fix #<gh-issue-id>
Test URLs:
- After: https://storytellerPlayButton--esri-eds--esri.aem.live/
=> Storyteller play button style

eds/blocks/hero/hero.js, eds/blocks/storyteller/storyteller.js, eds/scripts/dom-helpers.js, eds/scripts/scripts.js
Test URLs:
About overview page (fixed):
Original: https://www.esri.com/en-us/about/about-esri/overview
Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/overview
After: https://improvement-hero--esri-eds--esri.aem.live/en-us/about/about-esri/overview
Page without video (unchanged):
Before: https://main--esri-eds--esri.aem.live/drafts/timw/new-hero/visualization-interpretation
After: https://improvement-hero--esri-eds--esri.aem.live/drafts/timw/new-hero/visualization-interpretation
=> Fix hero video + refactor hero

.stylelintrc.json, package-lock.json, package.json
Updated Stylelint rules to validate selector and ID patterns to ensure they conform to the BEM convention. I also updated the Stylelint dependencies in the `package.json` file to fix an issue preventing the pattern-matching rules from validating.
Fix #327
Test URLs:
- After: https://build-update-stylelint-config--esri-eds--esri.aem.live/
=> build: update stylelint config

eds/blocks/location-presence/location-presence.css, eds/blocks/map/map.css
Fixed invalid shorthand properties and formatting issues in the component's CSS files.
Fix #329
Test URLs:
- Before: https://main--esri-eds--esri.aem.page/
- After: https://329-styles-invalid-shorthand-properties--esri-eds--esri.aem.live/
=> fix: invalid shorthand properties and formatting

eds/styles/styles.css
Fix no issue number
Test URLs:
- After: https://filterUpdate--esri-eds--esri.aem.live/en-us/about/about-esri/technology
=> Filter update

eds/blocks/local-navigation/local-navigation.css
Fix #340 
Test URLs:
- After: https://localnav--esri-eds--esri.aem.live/
=> Localnav code refinement

eds/blocks/local-navigation/local-navigation.css, eds/scripts/scripts.js
Issue: #341 
Test URLs:
- After: https://localnavigationmetadata--esri-eds--esri.aem.live/en-us/about/about-esri/overview
=> Use metadata to add local navigation

eds/blocks/local-navigation/local-navigation.css
Fix 
Test URLs:
- After: https://unstick--esri-eds--esri.aem.live/
=> feat(temporary): remove sticky from nav

eds/blocks/mosaic-reveal/mosaic-reveal.css
Fix #365 
Test URLs:
- After: https://reveal--esri-eds--esri.aem.live/
=> Reveal hover color and small refactor

eds/blocks/local-navigation/local-navigation.css
Uncomment sticky property
Fix #341 
Test URLs:
- After: https://sticknav--esri-eds--esri.aem.page/en-us/capabilities/data-management
=> feat: add sticky back in

eds/blocks/media-gallery/media-gallery.css, eds/styles/styles.css
Swap opacity var
alphabetized properties
Fix #372 
Test URLs:
- After: https://gallery--esri-eds--esri.aem.live/
=> feat: swap opacity variables light/dark; organize file

eds/blocks/media-gallery/media-gallery.css, eds/blocks/media-gallery/media-gallery.js
Need to allow for Category as first text item
Fix #354
Test URLs:
- After: https://gallerycategory--esri-eds--esri.aem.live/en-us/about/about-esri/overview
- After: https://gallerycategory--esri-eds--esri.aem.live/en-us/about/about-esri/overview
=> Add Gallery category

eds/blocks/media-gallery/media-gallery.js
Improve readability with braces and array destructuring.
Fix #354
Test URLs:
- After: https://gallery-refactor--esri-eds--esri.aem.live/
- After: https://gallery-refactor--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/overview
=> refactor(media-gallery): improve readability with braces and array destructuring

eds/styles/styles.css
Fix #381 
Test URLs:
- After: https://gridspace--esri-eds--esri.aem.live/en-us/about/about-esri/overview
=> feat: add leader trailer styles

eds/blocks/hero/hero.css
Fix #349 
Test URLs:
- After: https://heroupdates--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview
=> feat: fix banner height, font treatment

eds/blocks/elastic-content-strip/elastic-content-strip.css
Fix #360 
Test URLs:
- After: https://ecs--esri-eds--esri.aem.live/en-us/about/about-esri/americas
=> fix: ecs fonts, colors, spacing

eds/blocks/call-to-action/call-to-action.css, eds/blocks/call-to-action/call-to-action.js, eds/blocks/form/form.css, eds/blocks/form/form.js, eds/blocks/local-navigation/local-navigation.css
Includes barebones cta as a fragment implementation to ensure it does not break the display in mobile
Test URLs:
- After: https://dictionaryforms--esri-eds--esri.aem.live/en-us/capabilities/data-management
=> Implement dictionary-based form

eds/blocks/elastic-content-strip/elastic-content-strip.css
Fix sizes of panels for 1 - 3 panels in ECS. 
Current AEM component handles up to 6 panels. We can amend as needed. 
Fix #390
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/drafts/timw/test-page
- After: https://ecssize--esri-eds--esri.aem.live/drafts/timw/test-page
=> Elastic Content Strip panel sizes

eds/blocks/local-navigation/local-navigation.css, eds/blocks/local-navigation/local-navigation.js
Fix #413 
Test URLs:
- After: https://localnavbtn--esri-eds--esri.aem.live/en-us/capabilities/real-time/overview
=> Local Nav implement blue register get started button

eds/blocks/local-navigation/local-navigation.css, eds/blocks/local-navigation/local-navigation.js
Draw local navigation from overview folder if page selected is subfolder page
Fix #419
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/real-time/features/storage
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/storage
- After: https://navSubHomePg--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/storage
=> Local Nav find overview page for subfolder pages

eds/blocks/hero/hero.css, eds/blocks/hero/hero.js
Scenarios
- If Hero Banner has a Title, Subtitle and Description, convert Subtitle from p tag  h2 element and reduce Description font size from font-2 to font-0.
- If Hero Banner has a title and description than do nothing. 
Fix #421 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/3d-gis/overview
- After: https://heroH2--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/overview
=> Hero Banner Convert subtitle to an H2

eds/blocks/quote/quote.css, eds/blocks/quote/quote.js
Clean up css after icon change; fix icon color
Fix #435 
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/capabilities/management
- After: https://quote--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/capabilities/management
=> Quote cleanup & fix icon

eds/blocks/call-to-action/call-to-action.css, eds/blocks/call-to-action/call-to-action.js, eds/blocks/cards/cards.css, eds/blocks/cards/cards.js, eds/blocks/form/form.css, eds/blocks/form/form.js, eds/scripts/aem.js, eds/styles/styles.css
Test URLs:
**Actuation (contains form modal)**
Original: https://www.esri.com/en-us/capabilities/real-time/features/actuation
Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/actuation
After: https://feature-cta--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/actuation
**Data management**
Original: https://www.esri.com/en-us/capabilities/data-management
Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/data-management
After: https://feature-cta--esri-eds--esri.aem.live/en-us/capabilities/data-management
**3d-gis** 
Original: https://www.esri.com/en-us/capabilities/3d-gis/overview
Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/overview
After: …
=> Call to action + form modal

eds/blocks/hero/hero.css
Hero Banner Medium Format
Fix #434 
https://www.esri.com/en-us/capabilities/mapping/overview **(hero banner medium variant example)**
https://main--esri-eds--esri.aem.live/en-us/capabilities/mapping/overview **(hero banner medium variant example)**
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/3d-gis/overview
- After: https://medHero--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/overview
=> Hero Banner Medium Variant

eds/blocks/local-navigation/local-navigation.css, eds/scripts/color-filter.js, eds/scripts/scripts.js
Fix #450 and others
Test URLs:
- After: https://themecolor--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview
Page theme color output from page meta
convert to css vars
=> Themecolor

eds/blocks/cards/cards.css, eds/blocks/cards/cards.js
- Updated code so only the title of card is H3
- Updated code to adjust font size of card description when there is button/link inside the card.
Fix #464 
Test URLs:
- After: https://cardtitleh3--esri-eds--esri.aem.page/en-us/capabilities/indoor-gis/overview
=> Updated H3 and card description

eds/blocks/cards/cards.css
Fix #439
Test URLs:
- After: https://icon-filter--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/overview
=> feat: add theme filter to icons

eds/blocks/storyteller/storyteller.css, eds/blocks/storyteller/storyteller.js
Fixed layout issues and styles.
Fix #325 
Test URLs:
- After: https://325-storyteller-css--esri-eds--esri.aem.live/
=> fix(storyteller): layout and styles

eds/blocks/centered-content-switcher/centered-content-switcher.css
Fix #499 
Test URLs:
- After: https://ccswitcher--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview
=> Centered content switcher bg update

eds/blocks/mosaic-reveal/mosaic-reveal.js
Test URLs:
- After: https://fix-mosaicreveal--esri-eds--esri.aem.live/en-us/about/about-esri/americas
=> Fix mosaic reveal bug

eds/blocks/columns/columns.css, eds/blocks/columns/columns.js
Style playbutton and hide video url. No functionality yet.
Fix #514
Test URLs: (Media Text Split)
- Original: https://www.esri.com/en-us/capabilities/indoor-gis/capabilities/indoor-data-collection
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/capabilities/indoor-data-collection
- After: https://mtsModal--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/capabilities/indoor-data-collection
Test URLs: **(Media Split)**
- Original: https://www.esri.com/en-us/en-us/capabilities/geoai/overview
- After: https://mtsModal--esri-eds--esri.aem.live/en-us/capabilities/geoai/overview
Test URLs: (50-50)
- Before: …
=> Media Split Style Play Button 

eds/blocks/cards/cards.js
Fix #542 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/3d-gis/resources#immersive-experiences
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/resources#immersive-experiences
- After: https://cardstandardlink--esri-eds--esri.aem.live/en-us/capabilities/3d-gis/resources#immersive-experiences
=> card standard with calcite link

eds/blocks/columns/columns.css
Fix #553 
Test URLs:
- After: https://casestudy--esri-eds--esri.aem.live/en-us/capabilities/field-operations/overview
=> feat: case study component

eds/blocks/call-to-action/call-to-action.css
Fix #571 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/real-time/partners/cloud-iot-platforms
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/partners/cloud-iot-platforms
- After: https://ctaoverflow--esri-eds--esri.aem.live/en-us/capabilities/real-time/partners/cloud-iot-platforms
=> cta overflow fix

eds/blocks/large-content-stack/large-content-stack.css, eds/blocks/large-content-stack/large-content-stack.js
Append the Mediaspace link, create button, and launch modal. 
Fix #538
Test URLs:
- After: https://lcs--esri-eds--esri.aem.live/en-us/capabilities/indoor-gis/overview
Before: 
After:
=> feat: video link and modal

eds/styles/styles.css
Fix # none
Test URLs:
- After: https://cleanup--esri-eds--esri.aem.live/
=> chore: clean up lint issues

eds/blocks/call-to-action/call-to-action.css, eds/blocks/form/form.css, eds/blocks/form/form.js
Fix #575 
Test URLs-1:
- Original: https://www.esri.com/en-us/capabilities/real-time/partners/cloud-iot-platforms
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/partners/cloud-iot-platforms
- After: https://ctamodal--esri-eds--esri.aem.live/en-us/capabilities/real-time/partners/cloud-iot-platforms
Test URLS-2:
- Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/resources
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/resources
- After: https://ctamodal--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/resources
=> fix(ui): cta one form modal

eds/styles/styles.css
Fix #582 
Test URLs:
- After: https://cta--esri-eds--esri.aem.live/en-us/about/about-esri/americas
=> cta section styling

eds/blocks/centered-content-switcher/centered-content-switcher.css, eds/blocks/centered-content-switcher/centered-content-switcher.js
Switch from aria-hidden to 'hidden' property. 
Confirm component functions as normal.
Fix #559 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/americas#other-international
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/americas#other-international
- After: https://ccsHidden--esri-eds--esri.aem.live/en-us/about/about-esri/americas
=> Centered Content Switcher use Hidden Property

eds/blocks/cards/cards.css, eds/blocks/cards/cards.js
Added video play button for cards that has video
Fix #601 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/resources#analysis-and-ai
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/resources#analysis-and%20ai
- After: https://videocards--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/resources#analysis-and%20ai
=> Add play button for cards that has video

eds/blocks/mosaic-reveal/mosaic-reveal.js
Fix #607 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/locations
- Before: https://main--esri-eds--esri.aem.live/drafts/amallempati/locations
- After: https://mosaic--esri-eds--esri.aem.live/drafts/amallempati/locations
=> Add null checker for anchor inside mosaic reveal block

eds/blocks/map/map.css, eds/blocks/map/map.js, eds/styles/styles.css
Changes:
- [JS] Replaced IDs with classes.
- [JS] Modified `handleLoadFrame` and `handleLoadError` to use the event target to locate the specific instance of elements.
- [JS] Used DOM traversal with `closest()` to find the parent wrapper for the current instance.
- [JS] Changed to scoped queries instead of global document queries.
- [JS] Null/undefined checks were added for the heading and appended children.
- [JS] Removed the unused `defaultContentContainer` div.
- [JS] Optimized the `IntersectionObserver` settings to ensure each instance is properly scoped to its block.
- [CSS] Created new root-level variables for consistent sizes.
- [CSS] Replaced traditional properties with logical properties for better internationalization support and consistency.
- [CSS] Reorganized media queries to …
=> refactor(map-component): improve code and styling

eds/blocks/sidedrawer/sidedrawer.css, eds/blocks/sidedrawer/sidedrawer.js
The Sidedrawer block is correctly positioned and operating as intended, with the exception of the iframe not loading within the Sidedrawer container. The iframe functions properly once the CORS issues are resolved.
Fix #608 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/imagery-remote-sensing/overview
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/overview
- After: https://sidedrawer--esri-eds--esri.aem.live/en-us/capabilities/imagery-remote-sensing/overview
=> sidedrawer

eds/blocks/cards/cards.css
Remove code comments.
Fix sizing of checkmark icon.
Fix #617
Test URLs:
- After: https://dlclean--esri-eds--esri.aem.live/en-us/capabilities/real-time/overview
=> fix(detail list): remove comments, fix icon

eds/blocks/local-navigation/local-navigation.css, eds/blocks/local-navigation/local-navigation.js
Confirm dropdowns functions as normal. 
Fix #616
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/real-time/get-started
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/get-started
- After: https://navhidden--esri-eds--esri.aem.live/en-us/capabilities/real-time/get-started
=> Local Navigation Replace aria-hidden with hidden

eds/blocks/hero/hero.css, eds/blocks/hero/hero.js
Fix #275 
Test URLs:
- Original: https://www.esri.com/en-us/digital-transformation/overview
- Before: https://main--esri-eds--esri.aem.live/en-us/digital-transformation/overview
- After: https://hero--esri-eds--esri.aem.live/en-us/digital-transformation/overview
- After: https://hero--esri-eds--esri.aem.live/en-us/about/about-esri/overview
=> Hero foreground update

eds/blocks/hero/hero.css, eds/blocks/hero/hero.js
Fix #275 
Test URLs:#1
- After: https://herofg--esri-eds--esri.aem.live/en-us/about/about-esri/overview
Test URLs:#2
- Original: https://www.esri.com/en-us/digital-transformation/overview
- Before: https://main--esri-eds--esri.aem.live/en-us/digital-transformation/overview
- After: https://herofg--esri-eds--esri.aem.live/en-us/digital-transformation/overview
Test URLs:#3
- Original: https://www.esri.com/en-us/about/about-esri/locations
- Before: …
=> fix the hero block

eds/blocks/storyteller/storyteller.css, eds/blocks/storyteller/storyteller.js, eds/scripts/scripts.js
- Updated JS so the play/pause controls work as expected.
- Progess circle shows the progress of the video.
- Functions the same as prod.
- Loopa attribute will be fixed as part of an other issue.
Fix #653 
Test URLs:
- After: https://stplaycontrols--esri-eds--esri.aem.live/en-us/about/about-esri/overview
=> Story teller video controls[Issue#653]

eds/blocks/mosaic-reveal/mosaic-reveal.css, eds/blocks/mosaic-reveal/mosaic-reveal.js
Fix #677 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/mea-central-asia
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/mea-central-asia
- After: https://mosaicrevealupdate--esri-eds--esri.aem.live/en-us/about/about-esri/mea-central-asia
=> fix(ui): mosaic reveal updates [#677]

eds/blocks/media-gallery/media-gallery.css
Fix #685 
Test URLs:
- After: https://mghover--esri-eds--esri.aem.live/en-us/about/about-esri/overview
=> fix(mg card): added a zoom effect for mg on hover[#685]

eds/scripts/delayed.js, eds/styles/styles.css
Fix #687 
Test URLs:
- After: https://closeIcon--esri-eds--esri.aem.live/en-us/about/about-esri/overview
=> Modal Close Button - Calcite Icon Size a size too big

eds/blocks/hero/hero.css
Fix #698 
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/drafts/timw/americas
- After: https://centerhero--esri-eds--esri.aem.live/drafts/timw/americas
=> Center hero

eds/blocks/centered-content-switcher/centered-content-switcher.js, eds/scripts/delayed.js
Center Content Switcher (two modals appear on click)
Fix #694 
Test URLs:
- After: https://ccsDble--esri-eds--esri.aem.live/en-us/about/about-esri/americas
=> Center Content Switcher Duplicate Modals

eds/blocks/video/video.css, eds/blocks/video/video.js
Added out of the box video block.
Fix #702 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/asia-pacific
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/asia-pacific
- After: https://videoblock--esri-eds--esri.aem.live/en-us/about/about-esri/asia-pacific
=> Video block ootb[#702]

eds/blocks/mosaic-reveal/mosaic-reveal.css, eds/blocks/storyteller/storyteller.css
Update breakpoint for story teller grid and adjusted spacing.
Fix #711 
Test URLs:
- After: https://stbreakpoint--esri-eds--esri.aem.live/en-us/about/about-esri/overview
=> fix(story teller): story teller breakpoint update[#711]

eds/blocks/cards/cards.css
Fix #738
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/americas#esri-events
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/americas#esri-events
- After: https://card--esri-eds--esri.aem.live/en-us/about/about-esri/americas#esri-events
=> fix(card): title fix bold and spacing

eds/styles/styles.css
Fix #742 
Test URLs:
- After: https://buttonsecondary--esri-eds--esri.aem.live/en-us/about/about-esri/technology
=> fix(ui): button secondary border width update[#742]

eds/blocks/call-to-action/call-to-action.css
Fix #720 
Test URLs:
- After: https://ctabuttoncolor--esri-eds--esri.aem.live/en-us/about/about-esri/overview
=> fix(ui): cta block button color[#720]

eds/blocks/local-navigation/local-navigation.css, eds/blocks/local-navigation/local-navigation.js
Fix #744 
Test URLs:
- Original: https://www.esri.com/en-us/capabilities/real-time/features/ingestion
- Before: https://main--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/ingestion
- After: https://localChev--esri-eds--esri.aem.live/en-us/capabilities/real-time/features/ingestion
=> Local Nav convert caret to chevron to match PROD.

eds/blocks/call-to-action/call-to-action.css
Fix #728 
Test URLs:
- Original: https://www.esri.com/en-us/about/about-esri/technology#learn-more-about-esri
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/technology#learn-more-about-esri
- After: https://ctaspace--esri-eds--esri.aem.live/en-us/about/about-esri/technology#learn-more-about-esri
=> fix(cta): reduce padding

eds/blocks/large-content-stack/large-content-stack.css
Fix #751 
Test URLs:
- Before: https://main--esri-eds--esri.aem.live/en-us/about/about-esri/company
- After: https://updates--esri-eds--esri.aem.live/en-us/about/about-esri/company
=> fix(lcs): remove font-weight normal

eds/blocks/mosaic-reveal/mosaic-reveal.css, eds/blocks/mosaic-reveal/mosaic-reveal.js
Fix #765 
Test URLs:
- After: https://mosaic--esri-eds--esri.aem.live/en-us/about/about-esri/americas
=> fix(Mosaic): Add category flag

eds/blocks/storyteller/storyteller.css
Just add css for h3 in StoryTeller
Fix #<gh-issue-id>
Test URLs:
- After: https://sticons--esri-eds--esri.aem.live/en-us/about/about-esri/technology
=> feat(st): add style for h3

eds/blocks/storyteller/storyteller.css
Fix #770 
Test URLs:
- After: https://sticonstyles--esri-eds--esri.aem.live/en-us/about/about-esri/technology
=> fix(storyteller): story teller icon styles and alignment[#770]
